A failed run

What is wrong with our logic? line 5 only stops when n is equal to 2
Why doesn't the function stop calling itself? for odd numbers n will never equal 2
What's happening to the value of 'n' as the function gets deeper and deeper into recursion? n will get smaller and smaller until recursion depth is exceeded.


C:\Users\bjwarren\Documents\SchoolProjects\python220\SP_Online_Course2_2018\students\imaStudent\lesson05\recursion\recursion>python -m pdb recursion.py 9
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(2)<module>()
-> import sys
(Pdb) ll
  1
  2  -> import sys
  3
  4     def my_fun(n):
  5         if n == 2:
  6             return True
  7
  8         return my_fun(n/2)
  9
 10
 11     if __name__ == '__main__':
 12         n = int(sys.argv[1])
 13         print(my_fun(n))
(Pdb) b 5
Breakpoint 1 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:5
(Pdb) b 13
Breakpoint 2 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:13
(Pdb) cont
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(13)<module>()
-> print(my_fun(n))
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
9
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(8)my_fun()
-> return my_fun(n/2)
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
4.5
(Pdb) cont
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
2.25
(Pdb) c
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
1.125
(Pdb) c
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
0.5625
(Pdb) c
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
0.28125
(Pdb) cl 1
Deleted breakpoint 1 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:5
(Pdb) c
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "C:\Program Files (x86)\Python36-32\lib\pdb.py", line 1548, in _runscript
    self.run(statement)
  File "C:\Program Files (x86)\Python36-32\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py", line 13, in <module>
    print(my_fun(n))
  File "c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py", line 8, in my_fun
    return my_fun(n/2)
  File "c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py", line 8, in my_fun
    return my_fun(n/2)
  File "c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py", line 8, in my_fun
    return my_fun(n/2)
  [Previous line repeated 980 more times]
  File "c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py", line 4, in my_fun
    def my_fun(n):
  File "C:\Program Files (x86)\Python36-32\lib\bdb.py", line 50, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "C:\Program Files (x86)\Python36-32\lib\bdb.py", line 76, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):
  File "C:\Program Files (x86)\Python36-32\lib\bdb.py", line 173, in break_anywhere
    return self.canonic(frame.f_code.co_filename) in self.breaks
  File "C:\Program Files (x86)\Python36-32\lib\bdb.py", line 29, in canonic
    if filename == "<" + filename[1:-1] + ">":
RecursionError: maximum recursion depth exceeded in comparison
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\program files (x86)\python36-32\lib\bdb.py(29)canonic()
-> if filename == "<" + filename[1:-1] + ">":
(Pdb)

A good run

C:\Users\bjwarren\Documents\SchoolProjects\python220\SP_Online_Course2_2018\students\imaStudent\lesson05\recursion\recursion>python -m pdb recursion.py 4
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(2)<module>()
-> import sys
(Pdb) ll
  1
  2  -> import sys
  3
  4     def my_fun(n):
  5         if n == 2:
  6             return True
  7
  8         return my_fun(n/2)
  9
 10
 11     if __name__ == '__main__':
 12         n = int(sys.argv[1])
 13         print(my_fun(n))
(Pdb) b 13
Breakpoint 1 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:13
(Pdb) b 5
Breakpoint 2 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:5
(Pdb) b 8
Breakpoint 3 at c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py:8
(Pdb) cont
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(13)<module>()
-> print(my_fun(n))
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
4
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(8)my_fun()
-> return my_fun(n/2)
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(5)my_fun()
-> if n == 2:
(Pdb) pp n
2.0
(Pdb)
2.0
(Pdb) n
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(6)my_fun()
-> return True
(Pdb) n
--Return--
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(6)my_fun()->True
-> return True
(Pdb) n
--Return--
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(8)my_fun()->True
-> return my_fun(n/2)
(Pdb) n
True
--Return--
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(13)<module>()->None
-> print(my_fun(n))
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) n
The program finished and will be restarted
> c:\users\bjwarren\documents\schoolprojects\python220\sp_online_course2_2018\students\imastudent\lesson05\recursion\recursion\recursion.py(2)<module>()
-> import sys
(Pdb) quit

